# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-01 21:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_id', models.CharField(max_length=1, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_planted', models.DateTimeField()),
                ('plant_name', models.CharField(max_length=128)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_num', models.IntegerField(unique=True)),
                ('in_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Lot')),
            ],
        ),
        migrations.AddField(
            model_name='plant',
            name='row',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Row'),
        ),
    ]
