# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-01 22:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lot',
            old_name='lot_id',
            new_name='lotid',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='date_planted',
            new_name='dateplanted',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='plant_name',
            new_name='plantname',
        ),
        migrations.RenameField(
            model_name='row',
            old_name='in_lot',
            new_name='inlot',
        ),
        migrations.RenameField(
            model_name='row',
            old_name='row_num',
            new_name='rownum',
        ),
    ]
