# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-01 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20190301_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='row',
            name='rownum',
            field=models.IntegerField(),
        ),
    ]
