# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-06 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20190301_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plant',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='row',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
