# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-09 00:20
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20190306_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='id',
            field=models.UUIDField(default=uuid.UUID('65ced67b-5fc6-4f1d-a5cc-37e7b3974c3b'), editable=False, primary_key=True, serialize=False),
        ),
    ]
