# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-11 17:53
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20190309_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='notes',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plant',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
