# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-30 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20190311_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
